### ISSUE TITLE
Reference other source for good Intro to regex

### ISSUE THREAD

**Issue by johnisom** [dwyl/learn-regex#6]
Launch School has available on their open bookshelf the book "Introduction to Regular Expressions." It is a book targeted towards complete beginners at regex and covers regex for both Ruby and Javascript (the language used here).

Having gone through it without any previous experience in regex, I can attest that it is a great starting point for learning all about regex in a comprehensive, mastery-based way. It's thorough and well written.

I am suggesting that this be added as an easy-to-understand, comprehensive introduction and additional read

It can be accessed [here](https://launchschool.com/books/regex).

**Comment by nelsonic** [comment]
Definitely a good resource. please PR. 👍
